test

diff --git a/.cloudbees/workflows/my-automation-2.yaml b/.cloudbees/workflows/my-automation-2.yaml
--- a/.cloudbees/workflows/my-automation-2.yaml
+++ b/.cloudbees/workflows/my-automation-2.yaml
@@ -1,39 +1,45 @@
 apiVersion: automation.cloudbees.io/v1alpha1
 kind: workflow
-name: My automation
+name: Jira-Enforced Workflow
 on:
   push:
     branches:
       - main
-jobs:
-  Checkout:
-    steps:
-      - name: Checkout
-        uses: cloudbees-io/checkout@v1
 
+jobs:
   Build:
-    needs: Checkout
     steps:
       - name: Configure git
         uses: docker://alpine/git:latest
         run: |
           git config --global --add safe.directory /cloudbees/workspace
-      - name: Checkout
-        uses: cloudbees-io/checkout@v1
-        
-      - name: Build 
-        uses: docker://maven:3-eclipse-temurin-17
-        run: |
-          mvn clean install 
-  Evidence:
-    needs: CommitInfoStage
-    steps:
-      - id: testAction
-        name: Test publish-evidence-item action
-        uses: cloudbees-io/publish-evidence-item@v1
-        with:
-         content: |
-           - Run ID: ${{ cloudbees.run_id }}
 
-           
-        
+      - name: Checkout Code
+        uses: cloudbees-io/checkout@v1
+
+      - name: Validate Commit Message
+        uses: docker://alpine/git:latest
+        run: |
+          commit_message=$(git log -1 --pretty=%B)
+          if ! [[ $commit_message =~ CBDEMO-[0-9]+ ]]; then
+            echo "Error: Commit message must contain the Jira issue key (e.g., CBDEMO-152)"
+            exit 1
+          fi
+
+      - name: Build with Maven
+        uses: docker://maven:3-eclipse-temurin-17
+        run: mvn clean install
+        shell: sh
+
+  SonarQubeScan:
+    needs: Build
+    steps:
+      - name: Checkout Code
+        uses: cloudbees-io/checkout@v1
+
+      - name: SonarQube Scan
+        uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v1
+        with:
+          sonar-exclusion: src/main/java
+          cover-file-name: ./pom.xml
+          language: "LANGUAGE_JAVA"
